### ISSUE TITLE
Unable to get Boss Key in Key Dungeon (3rd dungeon)

### ISSUE THREAD

**Issue by liftedplane** [ihm-tswow/Links-Awakening-DX-HD#37]
I know you're supposed to dash then jump across the 3 holes, but no matter how much of a running start or even with the piece of power that makes you move a little faster it's impossible to make the jump. Unless I'm missing something. I just tried for 20 minutes every single thing I could think of to jump the gap.

**Comment by hugojmaia** [comment]
Use the boot, jump right before the hole.
DON'T touch the d-pad during the whole process and you will make the jump.

This is something I've noticed, pressing any direction will cut down the jump distance.

**Comment by liftedplane** [comment]
thanks, I don't know why I didn't think to try that. I can't remember if it was like that in the original or not, I don't think so though.

**Comment by filipe-maia** [comment]
This issue is **being solved** or is **solved** here:
https://github.com/BigheadSMZ/Links-Awakening-DX-HD

Please report more issues (if you find them) here:
https://github.com/BigheadSMZ/Links-Awakening-DX-HD/issues
For more information read:
https://github.com/ihm-tswow/Links-Awakening-DX-HD/issues/50
